package com.techelevator;

public class Headlight extends AutoPart {
	private int lumens;
	private int lifeInHours;
	
	//autogenerated constructor needs member variables added to it.
	//also ask yourself if all the args are really needed to make a valid instance of object. in this case need them all
	
	public Headlight(int lumens, int lifeInHours, String partNumber, String name, String manufacturer, float weight, float price) {
		super(partNumber, name, manufacturer, weight, price);
		
		this.lumens = lumens;
		this.lifeInHours = lifeInHours;
	}
	
	//member variables won't change over life of product so only make getters
	
	public int getLumens() {
		return lumens;
	}
	
	public int getLifeInHours() {
		return lifeInHours;
	}

}
